package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Aeropuertos generated by hbm2java
 */
public class Aeropuertos implements java.io.Serializable {

	private int id;
	private boolean bolActivo;
	private int ciudad;
	private String nombre;

	public Aeropuertos() {
	}

	public Aeropuertos(int id, boolean bolActivo, int ciudad) {
		this.id = id;
		this.bolActivo = bolActivo;
		this.ciudad = ciudad;
	}

	public Aeropuertos(int id, boolean bolActivo, int ciudad, String nombre) {
		this.id = id;
		this.bolActivo = bolActivo;
		this.ciudad = ciudad;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public int getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(int ciudad) {
		this.ciudad = ciudad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
