package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Aerolineas generated by hbm2java
 */
public class Aerolineas implements java.io.Serializable {

	private int id;
	private Boolean bolActivo;
	private String nombre;
	private String tipoVuelos;

	public Aerolineas() {
	}

	public Aerolineas(int id) {
		this.id = id;
	}

	public Aerolineas(int id, Boolean bolActivo, String nombre, String tipoVuelos) {
		this.id = id;
		this.bolActivo = bolActivo;
		this.nombre = nombre;
		this.tipoVuelos = tipoVuelos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Boolean getBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(Boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipoVuelos() {
		return this.tipoVuelos;
	}

	public void setTipoVuelos(String tipoVuelos) {
		this.tipoVuelos = tipoVuelos;
	}

}
