package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Asientos generated by hbm2java
 */
public class Asientos implements java.io.Serializable {

	private int id;
	private int avionId;
	private boolean bolActivo;
	private boolean libre;
	private int numero;
	private int reservaId;
	private int tipoClaseId;

	public Asientos() {
	}

	public Asientos(int id, int avionId, boolean bolActivo, boolean libre, int numero, int reservaId, int tipoClaseId) {
		this.id = id;
		this.avionId = avionId;
		this.bolActivo = bolActivo;
		this.libre = libre;
		this.numero = numero;
		this.reservaId = reservaId;
		this.tipoClaseId = tipoClaseId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAvionId() {
		return this.avionId;
	}

	public void setAvionId(int avionId) {
		this.avionId = avionId;
	}

	public boolean isBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public boolean isLibre() {
		return this.libre;
	}

	public void setLibre(boolean libre) {
		this.libre = libre;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public int getReservaId() {
		return this.reservaId;
	}

	public void setReservaId(int reservaId) {
		this.reservaId = reservaId;
	}

	public int getTipoClaseId() {
		return this.tipoClaseId;
	}

	public void setTipoClaseId(int tipoClaseId) {
		this.tipoClaseId = tipoClaseId;
	}

}
