package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Aviones generated by hbm2java
 */
public class Aviones implements java.io.Serializable {

	private int id;
	private int aerolineaId;
	private boolean bolActivo;
	private int capacidad;
	private String modelo;
	private int numeroAsientos;

	public Aviones() {
	}

	public Aviones(int id, int aerolineaId, boolean bolActivo, int capacidad, int numeroAsientos) {
		this.id = id;
		this.aerolineaId = aerolineaId;
		this.bolActivo = bolActivo;
		this.capacidad = capacidad;
		this.numeroAsientos = numeroAsientos;
	}

	public Aviones(int id, int aerolineaId, boolean bolActivo, int capacidad, String modelo, int numeroAsientos) {
		this.id = id;
		this.aerolineaId = aerolineaId;
		this.bolActivo = bolActivo;
		this.capacidad = capacidad;
		this.modelo = modelo;
		this.numeroAsientos = numeroAsientos;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getAerolineaId() {
		return this.aerolineaId;
	}

	public void setAerolineaId(int aerolineaId) {
		this.aerolineaId = aerolineaId;
	}

	public boolean isBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public int getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(int capacidad) {
		this.capacidad = capacidad;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public int getNumeroAsientos() {
		return this.numeroAsientos;
	}

	public void setNumeroAsientos(int numeroAsientos) {
		this.numeroAsientos = numeroAsientos;
	}

}
