package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Ciudades generated by hbm2java
 */
public class Ciudades implements java.io.Serializable {

	private int id;
	private boolean bolActivo;
	private String nombre;

	public Ciudades() {
	}

	public Ciudades(int id, boolean bolActivo) {
		this.id = id;
		this.bolActivo = bolActivo;
	}

	public Ciudades(int id, boolean bolActivo, String nombre) {
		this.id = id;
		this.bolActivo = bolActivo;
		this.nombre = nombre;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
