package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Itinerarios generated by hbm2java
 */
public class Itinerarios implements java.io.Serializable {

	private int id;
	private int segmento;
	private int vueloId;

	public Itinerarios() {
	}

	public Itinerarios(int id, int segmento, int vueloId) {
		this.id = id;
		this.segmento = segmento;
		this.vueloId = vueloId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getSegmento() {
		return this.segmento;
	}

	public void setSegmento(int segmento) {
		this.segmento = segmento;
	}

	public int getVueloId() {
		return this.vueloId;
	}

	public void setVueloId(int vueloId) {
		this.vueloId = vueloId;
	}

}
