package com.vuelos.model;
// Generated 05-Jun-2018 16:17:19 by Hibernate Tools 5.1.7.Final

/**
 * Piloto generated by hbm2java
 */
public class Piloto implements java.io.Serializable {

	private int idpiloto;
	private String nombre;

	public Piloto() {
	}

	public Piloto(int idpiloto) {
		this.idpiloto = idpiloto;
	}

	public Piloto(int idpiloto, String nombre) {
		this.idpiloto = idpiloto;
		this.nombre = nombre;
	}

	public int getIdpiloto() {
		return this.idpiloto;
	}

	public void setIdpiloto(int idpiloto) {
		this.idpiloto = idpiloto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
