package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Reservas generated by hbm2java
 */
public class Reservas implements java.io.Serializable {

	private int id;
	private int costo;
	private int numeroBoleto;
	private int usuarioId;

	public Reservas() {
	}

	public Reservas(int id, int costo, int numeroBoleto, int usuarioId) {
		this.id = id;
		this.costo = costo;
		this.numeroBoleto = numeroBoleto;
		this.usuarioId = usuarioId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getCosto() {
		return this.costo;
	}

	public void setCosto(int costo) {
		this.costo = costo;
	}

	public int getNumeroBoleto() {
		return this.numeroBoleto;
	}

	public void setNumeroBoleto(int numeroBoleto) {
		this.numeroBoleto = numeroBoleto;
	}

	public int getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(int usuarioId) {
		this.usuarioId = usuarioId;
	}

}
