package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

/**
 * Tarifas generated by hbm2java
 */
public class Tarifas implements java.io.Serializable {

	private int id;
	private boolean bolActivo;
	private int ciudadDestinoId;
	private int ciudadOrigenId;
	private int valorDirecto;
	private int valorItinerario;

	public Tarifas() {
	}

	public Tarifas(int id, boolean bolActivo, int ciudadDestinoId, int ciudadOrigenId, int valorDirecto,
			int valorItinerario) {
		this.id = id;
		this.bolActivo = bolActivo;
		this.ciudadDestinoId = ciudadDestinoId;
		this.ciudadOrigenId = ciudadOrigenId;
		this.valorDirecto = valorDirecto;
		this.valorItinerario = valorItinerario;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean isBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public int getCiudadDestinoId() {
		return this.ciudadDestinoId;
	}

	public void setCiudadDestinoId(int ciudadDestinoId) {
		this.ciudadDestinoId = ciudadDestinoId;
	}

	public int getCiudadOrigenId() {
		return this.ciudadOrigenId;
	}

	public void setCiudadOrigenId(int ciudadOrigenId) {
		this.ciudadOrigenId = ciudadOrigenId;
	}

	public int getValorDirecto() {
		return this.valorDirecto;
	}

	public void setValorDirecto(int valorDirecto) {
		this.valorDirecto = valorDirecto;
	}

	public int getValorItinerario() {
		return this.valorItinerario;
	}

	public void setValorItinerario(int valorItinerario) {
		this.valorItinerario = valorItinerario;
	}

}
