package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private boolean bolActivo;
	private String clave;
	private boolean clienteFrecuente;
	private int fechaExpira;
	private Date fechaNacimiento;
	private Date fechaRegistro;
	private String nombre;
	private String rut;
	private int tarjeta;

	public Usuarios() {
	}

	public Usuarios(boolean bolActivo, boolean clienteFrecuente, int fechaExpira, int tarjeta) {
		this.bolActivo = bolActivo;
		this.clienteFrecuente = clienteFrecuente;
		this.fechaExpira = fechaExpira;
		this.tarjeta = tarjeta;
	}

	public Usuarios(boolean bolActivo, String clave, boolean clienteFrecuente, int fechaExpira, Date fechaNacimiento,
			Date fechaRegistro, String nombre, String rut, int tarjeta) {
		this.bolActivo = bolActivo;
		this.clave = clave;
		this.clienteFrecuente = clienteFrecuente;
		this.fechaExpira = fechaExpira;
		this.fechaNacimiento = fechaNacimiento;
		this.fechaRegistro = fechaRegistro;
		this.nombre = nombre;
		this.rut = rut;
		this.tarjeta = tarjeta;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public boolean isBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public boolean isClienteFrecuente() {
		return this.clienteFrecuente;
	}

	public void setClienteFrecuente(boolean clienteFrecuente) {
		this.clienteFrecuente = clienteFrecuente;
	}

	public int getFechaExpira() {
		return this.fechaExpira;
	}

	public void setFechaExpira(int fechaExpira) {
		this.fechaExpira = fechaExpira;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	public int getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(int tarjeta) {
		this.tarjeta = tarjeta;
	}

}
