package com.vuelos.model;
// Generated 17-Jul-2018 15:04:21 by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Vuelos generated by hbm2java
 */
public class Vuelos implements java.io.Serializable {

	private int id;
	private Integer aerolineaId;
	private Integer avionId;
	private Boolean bolActivo;
	private Integer destinoId;
	private Boolean directo;
	private Boolean esItinerario;
	private String estadoVuelo;
	private Date horario;
	private Integer origenId;
	private Integer reservaId;
	private Integer precio;
	private String tipoVuelo;

	public Vuelos() {
	}

	public Vuelos(int id) {
		this.id = id;
	}

	public Vuelos(int id, Integer aerolineaId, Integer avionId, Boolean bolActivo, Integer destinoId, Boolean directo,
			Boolean esItinerario, String estadoVuelo, Date horario, Integer origenId, Integer reservaId, Integer precio,
			String tipoVuelo) {
		this.id = id;
		this.aerolineaId = aerolineaId;
		this.avionId = avionId;
		this.bolActivo = bolActivo;
		this.destinoId = destinoId;
		this.directo = directo;
		this.esItinerario = esItinerario;
		this.estadoVuelo = estadoVuelo;
		this.horario = horario;
		this.origenId = origenId;
		this.reservaId = reservaId;
		this.precio = precio;
		this.tipoVuelo = tipoVuelo;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getAerolineaId() {
		return this.aerolineaId;
	}

	public void setAerolineaId(Integer aerolineaId) {
		this.aerolineaId = aerolineaId;
	}

	public Integer getAvionId() {
		return this.avionId;
	}

	public void setAvionId(Integer avionId) {
		this.avionId = avionId;
	}

	public Boolean getBolActivo() {
		return this.bolActivo;
	}

	public void setBolActivo(Boolean bolActivo) {
		this.bolActivo = bolActivo;
	}

	public Integer getDestinoId() {
		return this.destinoId;
	}

	public void setDestinoId(Integer destinoId) {
		this.destinoId = destinoId;
	}

	public Boolean getDirecto() {
		return this.directo;
	}

	public void setDirecto(Boolean directo) {
		this.directo = directo;
	}

	public Boolean getEsItinerario() {
		return this.esItinerario;
	}

	public void setEsItinerario(Boolean esItinerario) {
		this.esItinerario = esItinerario;
	}

	public String getEstadoVuelo() {
		return this.estadoVuelo;
	}

	public void setEstadoVuelo(String estadoVuelo) {
		this.estadoVuelo = estadoVuelo;
	}

	public Date getHorario() {
		return this.horario;
	}

	public void setHorario(Date horario) {
		this.horario = horario;
	}

	public Integer getOrigenId() {
		return this.origenId;
	}

	public void setOrigenId(Integer origenId) {
		this.origenId = origenId;
	}

	public Integer getReservaId() {
		return this.reservaId;
	}

	public void setReservaId(Integer reservaId) {
		this.reservaId = reservaId;
	}

	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

	public String getTipoVuelo() {
		return this.tipoVuelo;
	}

	public void setTipoVuelo(String tipoVuelo) {
		this.tipoVuelo = tipoVuelo;
	}

}
